### ISSUE TITLE
Simplify FAQ/errata search

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/library#104]
Great job on adding FAQ/errata options for advanced search! There are a lot of options on them that aren't really needed—all we need essentially are "Has Errata" (>0) and "Has FAQ" and "Doesn't Have Errata (0)" and "Doesn't Have FAQ." I can't imagine any use cases for the other operators.

**Comment by seiyria** [comment]
This is fair. I was originally thinking of doing it this way, but I was torn between the screen presence a checkbox has vs. the other numerical operators, and the uncertainty of not knowing who might want to search for things with a lot of entries for whatever reason (did you know, Oath has two cards with >5 FAQ entries? yowza!). I figured I'd try to err on the side of caution but it is the stranger choice, I agree. They're now checkboxes.
