### ISSUE TITLE
Multiple FAQ/errata entries on Advanced Search page

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/library#105]
<img width="1105" alt="Screenshot 2024-06-27 at 3 03 09 PM" src="https://github.com/LederCards/library/assets/65436647/fc8ec96e-8572-4e33-974f-549229396167">

By entering and leaving the Advanced Search page—I believe it mostly happens when I switch games in between—I can get multiple entries of FAQ/errata Advanced Search options. It also introduces notable lag and juttering.

**Comment by seiyria** [comment]
This will likely no longer be an issue, as FAQ/Errata are no longer numerical operators. Let me know if this crops back up!
