### ISSUE TITLE
Text view should be printable

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/library#106]
If I try to print the Text view, whether directly or as a PDF, it comes out garbled or blank. Ideally, a user should be able to create a physical copy of this view. 

<img width="795" alt="Screenshot 2024-06-27 at 7 49 00 PM" src="https://github.com/LederCards/library/assets/65436647/983c4fda-2197-4cda-878c-9d41d7dd8e55">

**Comment by seiyria** [comment]
One thing of note: it will only print the current page and the up-to-60 results. I'm a bit torn about how to do this but printing should reflect the current state of the page, so for a user it will make sense, I hope.
