### ISSUE TITLE
Splash page renders partially during Text view print

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/library#107]
![image](https://github.com/LederCards/library/assets/65436647/efb8b403-ba09-4460-859f-e2c8bf68874c)

When I try to print the Text view, part of the splash page ("Leder Card Library is...") peeks through.

**Comment by seiyria** [comment]
Interesting. This one depends on the nav stack, which this would only happen if you went from main screen to search to do this. I'll fix that.
