### ISSUE TITLE
[Bug] - Printing the FAQ after reaching it from a card shows parts of card graphics on the sides

### ISSUE THREAD

**Issue by imkSushi** [LederCards/library#117]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the bug

Printing the FAQ after reaching it from a card shows parts of card graphics on the sides. Notably, this doesn't happen if you go straight to the FAQ, or even if you just refresh the page (though notably the search parameters in the url changes from `?locale=en-US&productId=arcs#ARCS-BC04` to `?locale=en-US&productId=arcs&q=&d=images&s=name&b=asc&p=0` when you do that)

All screenshots have been taken in incognito mode, to reduce the odds that it is just my cookies being weird.

I'm on Windows 11 using Google Chrome 126.0.6478.127

My bet is that this is a similar bug to #40 and #107 (which are both closed, and I think slightly different)

Also, it may be an idea to stick `break-inside: avoid` on each `ion-item-group` so that the headers of each section don't get seperated from the Q&A below them when you try to print it.

### Expected behavior

Dark Mode:
![image](https://github.com/user-attachments/assets/e9a0e616-f3d0-45b1-a1b7-7743f7375aaf)
![image](https://github.com/user-attachments/assets/ff61f9fb-d0d1-4cf9-92f9-96c1441a9f20)

Light Mode:
![image](https://github.com/user-attachments/assets/97688567-4e17-424b-803f-7a659bb3249b)
![image](https://github.com/user-attachments/assets/8e5eac86-4324-4ab8-80aa-c3a2bd84f789)

### Current behavior

Dark Mode:
![image](https://github.com/user-attachments/assets/06e11222-67b1-4547-8612-88064bdfc8d6)
![image](https://github.com/user-attachments/assets/68e4aecc-f160-41f5-be26-25a0868a52c1)
etc.

Light Mode:
![image](https://github.com/user-attachments/assets/25d73f39-abd9-4169-bb6a-0925d30c13b0)
![image](https://github.com/user-attachments/assets/bb3e1caa-fad3-4fd3-8bf5-d8ca1af9f773)

### To Reproduce

1. Go to https://cards.ledergames.com/search?q=game:%22arcs%22&d=images&s=id&b=asc&p=0
![image](https://github.com/user-attachments/assets/f179ee8a-e6b5-4db3-b55d-756ab184958f)

2. Click on a card that has FAQ (e.g. Admin Union)
![image](https://github.com/user-attachments/assets/dc52244a-4999-4833-a031-2386fcbf5f01)

3. Click on the link to the FAQ
![image](https://github.com/user-attachments/assets/0f6740fd-1420-4f5a-98bb-3f73237a1b59)
![image](https://github.com/user-attachments/assets/f3e0ce7c-c8d7-40bb-8d1f-42b9e63bed58)

4. Press Ctrl-P
![image](https://github.com/user-attachments/assets/1600c1bf-4acc-4145-ad10-f2f640d39ab5)

### Platform

Web Browser - Chrome

**Comment by seiyria** [comment]
This is interesting: when emulating print media it doesn't show up, it only shows up when in a real print preview. Kinda silly. But anyway, this is related as you suspected. Printing with anything in ionic is an absolute pain in the ass, and requires basically excluding things as they come up. This is pretty straightforward to sort out, though!
