### ISSUE TITLE
[Arcs] Warden: Lords and Closed Economies

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#119]
Can we confirm:
In Closed Economy, a Regent Lord cannot tax a Vassal city under Imperial Control, even Outlaw Vassal
Also some adjacent points
- a Regent Lord is bound by Truce law when taxing a Regent Vassal
- an Outlaw Lord can always tax Vassal cities regardless of Empire presence

[https://boardgamegeek.com/thread/3328547/lord-of-the-clusterclosed-economy](https://boardgamegeek.com/thread/3328547/lord-of-the-clusterclosed-economy)

- [x] Apply ruling to Lord of the 1st Cluster F1603
- [x]  Apply ruling to Lord of the 2nd Cluster F1604
- [x]  Apply ruling to Lord of the 3rd Cluster F1605
- [x]  Apply ruling to Lord of the 4th Cluster F1606
- [x]  Apply ruling to Lord of the 5th Cluster F1607
- [x]  Apply ruling to Lord of the 6th Cluster F1608
- [x] Apply ruling to Closed Economy? F326

**Comment by jdyearsley** [comment]
Correct, the **cannot** keyword overrides all allowances, so all these cases are correct. Feel free to add these.

**Comment by ledergamesmatt** [comment]
added to faq240820
