### ISSUE TITLE
[Arcs] Refugee Free Cities and Cleared Outrage

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#122]
Are the refugee cards intended to mean "Build a Free city on a X planet you control. **_if you do..._**"
Is building the Free city required to clearing the Outrage and gaining the resources?

- [x] F1105
- [x] F1106
- [x] F1107
- [x] F1108
- [x] F1109

**Comment by jdyearsley** [comment]
Yes, the intent is you have to build the city.

**Comment by jdyearsley** [comment]
Added to file, production document, and branch!
