### ISSUE TITLE
[Arcs] Gate Ports and forced Moves

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#123]
[Force Beams](https://cards.ledergames.com/card/ARCS-L16?q=force%20beams) does not trigger [Gate Ports](https://cards.ledergames.com/card/ARCS-L08?q=gate%20ports). But does [Unstable Seeker](https://cards.ledergames.com/card/ARCS-F509?q=unstable%20seeker) or [Judge's Chosen](https://cards.ledergames.com/card/ARCS-F2404)?

**Comment by jdyearsley** [comment]
They do, since they don't state that they ignore **move** modifiers. It's a little goofy, sorry!

**Comment by ledergamesmatt** [comment]
added to Force Beams in faq240820
