### ISSUE TITLE
[Arcs] Court Ransack Trophies and the Admiral

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#126]
Do trophies taken as part of ransacking the court count towards Admiral's objective.
Is "Ransacking the court" a part of Battle?

**Comment by jdyearsley** [comment]
Yes, if Ransacking the Court is triggered by destroying a city in battle and not by some other means, I would count it as being part of the battle. You are destroying pieces in the battle, and Ransacking the Court happens as part of destroying a city. Feel free to add this clarification.

**Comment by ledergamesmatt** [comment]
added to faq240820
