### ISSUE TITLE
[Arcs] Ceasefire clarifications

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#130]
For [Ceasefires,](https://cards.ledergames.com/card/ARCS-F1508?q=game:arcs%20ceasefire) if a player plays a non-Aggression card to battle in a cluster at Peace, do they need to spend 1 or 2 Weapons? Is it one weapon per flip if a player wants to flip more than 1 Ceasefire token?

**Comment by jdyearsley** [comment]
Two Weapons for the first case, and one Weapon per flip. Feel free to clarify this!
