### ISSUE TITLE
[Arcs] "Like they are Loyal"

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#132]
These cards allows player to use non-Loyal buildings “like they are Loyal”

- Empath’s Bond (tax, build ship, catapult)
- Imperial Authority (tax)
- Member of Commonwealth (“take actions”)

Some cards refer to Loyal buildings

- Living Structure taxes Loyal cities and replaces Loyal buildings
- Anarchist cannot tax Loyal cities
- (Upstart does not refer to Loyal city anymore after errata)

So, can we confirm that all the cards that refer to taking actions with Loyal cities do not combine with the "like they are Loyal" cards.
Concretely this means

- Member of Commonwealth cannot tax / prune Free cities with Living Structure
- Anarchist can tax rival cities with Empath's Bond

And basically, "like they are Loyal" only serves as a short hand for "when you tax a city this way, you don't take a captive"

**Comment by jdyearsley** [comment]
This is all correct. The only addition is that "like they are Loyal" is also shorthand for "you don't need to control them." So in total, "like they are Loyal" -> "you don't take a Captive and you don't need to control them."

**Comment by ledergamesmatt** [comment]
Yeah, that's a nice simple way of putting it. This isn't really related to a single card, so is this better for the base game faq doc?

**Comment by jdyearsley** [comment]
Yes, feel free to stick this in the base game FAQ!
