### ISSUE TITLE
[Arcs] Judge's Chosen and Flagships

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#135]
[Judge's Chosen](https://cards.ledergames.com/card/ARCS-F2404) is ambiguous if the Judge has a Flagship. Is the Chosen allowed to perform all the actions granted by upgrades on the Judge's Flagships

**Comment by jdyearsley** [comment]
The Judge's Flagship is indeed their Loyal ship. You could use their Flagship to build ships, Catapult move, tax using Control Array, etc. Feel free to add this clarification!

**Comment by ledergamesmatt** [comment]
Added to FAQ-and-Errata-240820
