### ISSUE TITLE
[Arcs] Shaper and Cartels

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#136]
[Shaper](https://cards.ledergames.com/card/ARCS-LEAD14)'s Mythic ability says "a resource you have", implying you can use a resource off a Cartel card. Is this intended? Or should this be rephrased to be more like [Cloud Cities](https://cards.ledergames.com/card/ARCS-L09)?

**Comment by jdyearsley** [comment]
I think it's fine to use Cartel resources for Shaper. Feel free to put in this FAQ.

**Comment by ledergamesmatt** [comment]
added to faq240820
