### ISSUE TITLE
[Arcs] "stolen only as the card describes"

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#140]
> Some cards say they hold resources. These resources can be spent and add to ambitions, **but they can be stolen only as the card describes**...

The clause in bold is making some people think that if a card doesn't explicitly say the resource on it can be stolen, then they can't be stolen. Perhaps this can be rephrased.

**Comment by jdyearsley** [comment]
Hm, I'm not sure what this means—resources on cards don't have defined key costs, so they can't be stolen individually. (But the card, with the resources, can!) As an example, Fuel on [Fuel Cartel](https://cards.ledergames.com/card/ARCS-BC06?q=Cartel) couldn't be stolen. What is the specific confusion coming up?

**Comment by jdyearsley** [comment]
Ah, I see! Okay, this wording deserves a slight expansion to something like "can only be stolen in battle if the card allows it". I'll think through the errata here.

**Comment by jdyearsley** [comment]
Changed relevant portion of the core rulebook to "These resources can be spent and add to ambitions. They cannot be stolen in battle unless explicitly allowed." Added to production doc and base game FAQ.
