### ISSUE TITLE
[Arcs] Policy of Escalation when there's only a flagship

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#141]
If there is no empire-controlled system and the First Regent is a Flagship, does [Policy of Escalation](https://lederspotlight.netlify.app/card/ARCS-AID05) place ships at the Flagship if it has starport upgrade/armor? Thematically it makes sense but currently only Lore cards can count starports on the Flagship board as if in the system.

**Comment by jdyearsley** [comment]
I think the section of how Lore cards treat Flagship buildings should be expanded to include Edicts as well. There is at least one other case where this makes thematic sense. I'll add this as errata.

**Comment by jdyearsley** [comment]
Changed the relevant rulebook section title to "Cards & Flagships" and all references in this section from "Lore" to "Cards". After a look through all the Guild cards, this shouldn't mess up anything.

**Comment by jdyearsley** [comment]
Changed the relevant rulebook section title to "Cards & Flagships" and all references in this section from "Lore" to "Cards". After a look through all the Guild cards, this shouldn't mess up anything. Added to production doc and FAQ.
