### ISSUE TITLE
[Arcs] 2nd Place ambition after ties

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#142]
There is some dispute about what happens to the original 2nd place when players tie for 1st place. Rulebook doesn't explicitly state that second place gets nothing. Could use a clarification

**Comment by jdyearsley** [comment]
Fair! I'll see if I can put something explicit into the core rulebook without it mucking up too much.

**Comment by jdyearsley** [comment]
Added clarification "_(Other players do not place and gain no Power.)_" If you think this deserves an FAQ, go for it!

**Comment by ledergamesmatt** [comment]
I think rulebook errata will suffice
