### ISSUE TITLE
[Arcs] Pirate Hoard vs Free Cities

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#143]
[Pirate Hoard](https://cards.ledergames.com/card/ARCS-F1202) says "place resources you steal here", but when you raid the Free buildings, it is by definition gained, not stolen. Is there anything we can do about this that will make the rule as written consistent with the intention

**Comment by jdyearsley** [comment]
I think this is best addressed with a campaign rulebook change that says it counts as stealing for the purpose of card effects. The card itself already mentions you can raid Free buildings, which strongly implies that the resources go on this card.) Otherwise, just a card FAQ will do.

**Comment by jdyearsley** [comment]
Added "This counts as stealing." to the rulebook, production doc, and campaign FAQ.
