### ISSUE TITLE
[Arcs] Rogue Admirals Clarification

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#144]
There is some doubt on this: Can a Regent with [Rogue Admiral](https://lederspotlight.netlify.app/card/ARCS-F707) attack the Empire alone?

**Comment by jdyearsley** [comment]
Yes, and they can add any number of Imperial ships in the system to their attacking ships. Basically, they can pick and choose how many are attacking and how many are defending. (This is modeling the Empire breaking up into rival admiralties who each have a claim on the Empire's military, who's loyal, and who's a traitor.) This is likely unclear, so feel free to add a clarification.

**Comment by ledergamesmatt** [comment]
added to faq240820
