### ISSUE TITLE
[Arcs] Believer Ideal Markers

### ISSUE THREAD

**Issue by ledergamesmatt** [LederCards/library#145]
Similar to Planet Breaker Act 3 setup card, [Believer Act III Setup](https://cards.ledergames.com/card/ARCS-F829A) card should probably also have a step that says 

> Place ideal markers that were in ambition boxes back in them.

Or at least a FAQ about this

**Comment by jdyearsley** [comment]
Agreed. I'll put this in as errata.

**Comment by jdyearsley** [comment]
Added to file, production document, and branch!
