### ISSUE TITLE
Strip markdown syntax from card text during searches

### ISSUE THREAD

**Issue by emptierset** [LederCards/library#152]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the feature and its requirements

Issuing the query `t:"after scoring"` should find the Arcs Cartel cards, but it only finds the objective cards that contain this phrase without bold text. The problem is that the raw card text contains the phrase `After **scoring**`, so the mentioned query cannot find it. 

### Is your feature request related to an existing issue? Please describe.

No. 

### Is there anything stopping this feature being completed?

?

### Describe alternatives you've considered or encountered

I'm not aware of any way to work around this, because no (simple?) query finds all of the cards it should.

**Comment by jdyearsley** [comment]
Yes, I'd actually call this a bug. Could you take a look at this, @seiyria?
