### ISSUE TITLE
[Feature] - Display card image on Card page Discord Embed

### ISSUE THREAD

**Issue by harsch1** [LederCards/library#72]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the feature and its requirements

When embedding the page for a specific card on discord, use an embed that includes the card image instead of the standard "Leder Card Library" one. This would help with utility of the site when used in board game communities on Discord.

### Is your feature request related to an existing issue? Please describe.

No.

### Is there anything stopping this feature being completed?

I don't think so.

### Describe alternatives you've considered or encountered

The current alternative is for the user to open the link to the site itself to view the card.

**Comment by seiyria** [comment]
Not at this time. This would require me to use SSR or something else. I would like to do this, but I'm not sure how to do so with angular & netlify. I'll leave this issue open in the mean time in case someone does know a good way to do this.

**Comment by harsch1** [comment]
Would this be able to handle it? https://v17.angular.io/api/platform-browser/Meta

**Comment by seiyria** [comment]
Sorta. That only changes the metadata, whether or not it works depends on the renderer and if they pre-render the webpage or not. If they only look at the meta tags at time of page load, it won't work (which is where pre-rendering/ssr comes in). If they execute javascript on the page beforehand, it would work, but I haven't tested it with discord.

**Comment by seiyria** [comment]
Maybe prerendering the card pages would work: https://angular.dev/guide/prerendering

**Comment by seiyria** [comment]
This is now partially implemented. TODO eventually:

- output a version hash onto the app (md5 the card json data)
- add a nightly script that checks the current hash vs the production hash, if they do not match, trigger a full rebuild

**Comment by harsch1** [comment]
Looks great! Thank you so much for working on this issue!

**Comment by seiyria** [comment]
Any time the cards repo updates, it will now make the main repo update. Probably done in the least shenanigans-y way, which is excellent. README updated for anyone who ends up having to figure this out later, too.
