### ISSUE TITLE
Search carat and icon are separate with space in between

### ISSUE THREAD

**Issue by jdyearsley** [LederCards/library#78]
Currently, the game icon and search carat are separate objects. If you select one while the dropdown is active for the other, it removes the dropdown and triggers a new dropdown. There is also a small, nonselectable space between them. (Would it just be easier to put the carat in our game icon definitions?)

**Comment by tburrows13** [comment]
@seiyria it doesn't look like your change had any effect on how it behaves, I don't believe this has been fixed.

**Comment by seiyria** [comment]
@tburrows13 I'm going to need a reproduction. I have put both the caret and the selector on the same div, and moved the click event to that, and it works fine for me. You're probably going to have to clear your cache and try again.

**Comment by tburrows13** [comment]
https://github.com/LederCards/library/assets/22625968/08d2a73c-bf22-494f-93fc-1725aaf9c371

Here's what I mean. In my opinion, all 3 click locations should open the same dropdown in the same location, but in fact the first click opens a dropdown at the down-arrow, the second click(s) don't do anything, and the third click opens a dropdown at the logo.

This still occurs after clearing cache and force reloading the page (and I can confirm using inspect element that the elements _are_ in the div).

**Comment by seiyria** [comment]
That's a separate issue entirely. The original issue was that you could open two dropdowns by clicking the image and the caret, and that they weren't a united element. In terms of usability I'm not 100% sure I agree here, but I will adjust it.

**Comment by tburrows13** [comment]
Ah, I had missed the "If you select one while the dropdown is active for the other, it removes the dropdown and triggers a new dropdown." part in the original report. I presume that's what you fixed.

(FYI the original report was based on my report in the discord, although I hadn't noticed that bit specifically, which I why I thought nothing had changed in the behaviour :) )
