### ISSUE TITLE
[Bug] - Missing Believer action cards

### ISSUE THREAD

**Issue by tburrows13** [LederCards/library#80]
### Prerequisites

- [X] I have searched the issue tracker to check if the issue has already been reported.

### Describe the bug

Cards F04-F12 are missing.

### Expected behavior

Cards 04-12 appear (this is what they look like)
<img width="643" alt="Screenshot 2024-06-18 at 18 20 49" src="https://github.com/LederCards/spotlight/assets/22625968/5fa98ffa-c52c-49f0-81e8-6a8c546c0a73">

### Current behavior

Cards 04-12 do not appear.

### To Reproduce

Search with tag:"Believer" (https://cards.ledergames.com/search?q=tag:%22Believer%22&d=images&s=id&b=asc&p=0).

### Platform

Desktop

**Comment by ledergamesmatt** [comment]
Added card images
